[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mV"
version = "0.1.0"
requires-python = ">=3.7"


[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", ".lms*"]

[project.scripts]
mV = "mvbuild.src.main:main"